name: weather
version: 1.5.0
main: apart\weather\Main
api: 4.0.0
author: Apartkktrain

commands:
  weather:
    description: change the weather
    usage: /weather
    permission: weather.command.op
permissions:
  weather.command.op:
    default: op
    description: weather command permission
